### ISSUE TITLE
The example is broken

### ISSUE THREAD

**Issue by Mossaka** [fermyon/http-auth-middleware#19]
At the step of `spin build`, I have hit an error 

```
error: failed to connect instance `$input` to definition component `/Users/mossaka/Developer/mossaka/http-auth-middleware-go/example/target/wasm32-wasi/release/example.wasm`

Caused by:
    0: source instance export `wasi:http/incoming-handler@0.2.0-rc-2023-10-18` is not compatible with target instance import `wasi:http/incoming-handler@0.2.0-rc-2023-10-18`
```

I think this is due to some WASI HTTP spec change upstream. I also tried to pin the spin version to `v2.0.1` but it still doesn't work.

**Comment by voigt** [comment]
Demo is working for me with both, spin and Wasmtime (v14.0.4):

```
$ spin --version
spin 2.0.1 (1d72f1c 2023-11-10)
$ cargo-component --version
cargo-component 0.4.1 (2c772f3 2023-11-07 wasi:2da78ca)
```

**Comment by seungjin** [comment]
As of May 09 2024, the code here is broken with latest tool chains.

**Comment by fibonacci1729** [comment]
Sorry about that! This repo has lagged a bit behind the toolchains. I'll try to bring things up to date here in the comings days.
